prometheus: {}
controller:
  image:
    repository: quay.io/metallb/controller
    tag: v0.13.12

speaker:
  image:
    repository: quay.io/metallb/speaker
    tag: v0.13.12
  frr:
    image:
      repository: quay.io/frrouting/frr
      tag: 8.5.4
