apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: uptime-kuma
spec:
  routes:
    - match: Host(`uptime.s3rv.dev`)
      kind: Rule
      services:
        - name: uptime-kuma
          port: 3001