image:
  repository: docker.io/louislam/uptime-kuma
  pullPolicy: IfNotPresent
  tag: "1.23.10-debian"

podEnv:
  # a default port must be set. required by container
  - name: "UPTIME_KUMA_PORT"
    value: "3001"

volume:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClassName: nfs-client