containers:
  unbound:
    image:
      repository: ghcr.io/pixelfederation/unbound
      tag: 1.17.1_3
      pullPolicy: IfNotPresent
    config:
      verbosity: 0
      logReplies: "no"
      logQueries: "no"
      logTagQueryreply: "no"
      logLocalActions: "no"
      logServfail: "no"
      allowedIpRanges:
      - "10.96.0.0/12"
      - "10.244.0.0/16"
replicaCount: 1
