#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/a081de5/charts/library/common/values.yaml
#
image:
  repository: ghcr.io/paperless-ngx/paperless-ngx
  pullPolicy: IfNotPresent
  tag: 2.3.1

env:
  TZ: Europe/Berlin
  PAPERLESS_TIME_ZONE: Europe/Berlin
  PAPERLESS_OCR_LANGUAGE: deu
  PAPERLESS_DATE_ORDER: "DMY"
  PAPERLESS_TASK_WORKERS: 2
  PAPERLESS_THREADS_PER_WORKER: 2
  PAPERLESS_FILENAME_FORMAT: "{created_year}/{document_type}/{correspondent}/{title}"
  PAPERLESS_URL: https://paperless.s3rv.dev
  PAPERLESS_REDIS: redis://redis

service:
  main:
    ports:
      http:
        port: 8000

persistence:
  data:
    enabled: true
    mountPath: /usr/src/paperless/data
    storageClass: "nfs-client"
    accessMode: ReadWriteOnce
    size: 1Gi
  media:
    enabled: true
    mountPath: /usr/src/paperless/media
    storageClass: "nfs-client"
    accessMode: ReadWriteOnce
    size: 10Gi
  export:
    enabled: true
    mountPath: /usr/src/paperless/export
    storageClass: "nfs-client"
    accessMode: ReadWriteOnce
    size: 1Gi
  consume:
    enabled: true
    mountPath: /usr/src/paperless/consume
    storageClass: "nfs-client"
    accessMode: ReadWriteOnce
    size: 1Gi
    
redis:
  enabled: false